const mongoose = require('mongoose');
const Pet = require('scripts/petschema.js');

mongoose.connect('mongodb://localhost:27017/petco', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const pets = [
    {
        name: "Nemo",
        age: "5 Years",
        breed: "Shirazi",
        gender: "Male",
        neutered: "yes",
        location: "Cairo",
        image: "images/nemo.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Mimi",
        age: "3 Years",
        breed: "Shirazi",
        gender: "Female",
        neutered: "no",
        location: "Giza",
        image: "images/mimi.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Barbie",
        age: "1 Year",
        breed: "Shirazi",
        gender: "Female",
        neutered: "No",
        location: "Cairo",
        image: "images/barbie.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Minnie",
        age: "1 Year",
        breed: "Shirazi",
        gender: "Female",
        neutered: "No",
        location: "Cairo",
        image: "images/minnie.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Caramel",
        age: "3 Years",
        breed: "Shirazi",
        gender: "Female",
        neutered: "Yes",
        location: "Cairo",
        image: "images/caramel.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Bennetton",
        age: "1 Year",
        breed: "Shirazi",
        gender: "Female",
        neutered: "No",
        location: "Cairo",
        image: "images/bennetton.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Hadoota",
        age: "2 Years",
        breed: "Balady",
        gender: "Female",
        neutered: "No",
        location: "Ismailia",
        image: "images/hadoota.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Leila",
        age: "2 Years",
        breed: "Persian",
        gender: "Female",
        neutered: "No",
        location: "Port Said",
        image: "images/persian.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Luna",
        age: "3 Years",
        breed: "Ragdoll",
        gender: "Female",
        neutered: "Yes",
        location: "Alexandria",
        image: "images/ragdoll.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Snickers",
        age: "1 Year",
        breed: "Balady",
        gender: "Female",
        neutered: "No",
        location: "Cairo",
        image: "images/snickers.png",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Meshmesh & Simba",
        age: "2 Months",
        breed: "Shirazi/Balady",
        gender: "Female",
        neutered: "No",
        location: "Cairo",
        image: "images/twins.jpg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Monkey",
        age: "5 Years",
        breed: "Shirazi/Balady",
        gender: "Male",
        neutered: "No",
        location: "Giza",
        image: "images/monkey.jpg",
        type: "cat",
        upForAdoption: true
      },
      {
        name: "Snow",
        age: "3 Years",
        breed: "Shirazi",
        gender: "Male",
        neutered: "Yes",
        location: "Cairo",
        image: "images/snow.jpeg",
        type: "cat",
        upForAdoption: true
      },
      {
        name: "Tooty",
        age: "3 Years",
        breed: "Shirazi",
        gender: "Female",
        neutered: "No",
        location: "Ismailia",
        image: "images/tooty.jpg",
        type: "cat",
        upForAdoption: true
      },
      {
        name: "Bondo'",
        age: "6 Years",
        breed: "Shirazi/Balady",
        gender: "Male",
        neutered: "Yes",
        location: "Cairo",
        image: "images/bondo2.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Fangs",
        age: "3 Years",
        breed: "Shirazi",
        gender: "Male",
        neutered: "No",
        location: "Alexandria",
        image: "images/fangs.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Moro",
        age: "4 Months",
        breed: "Ragdoll",
        gender: "Male",
        neutered: "No",
        location: "Giza",
        image: "images/moro.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Kiara",
        age: "# Years",
        breed: "Ragdoll",
        gender: "Male",
        neutered: "No",
        location: "Giza",
        image: "images/moro.jpeg",
        type: "cat",
        upForAdoption: true,
      },
      {
        name: "Smokey",
        age: "1 Year",
        breed: "Labrador",
        gender: "Male",
        neutered: "No",
        location: "Cairo",
        image: "images/smokey.jpeg",
        type: "dog",
        upForAdoption: true
        },
        {
          name: "Astro",
          age: "1 Year",
          breed: "German Shepherd",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/astro.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Brownie",
          age: "4 Months",
          breed: "Dachshund",
          gender: "Male",
          neutered: "No",
          location: "Alexandria",
          image: "images/brownie.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Buddy",
          age: "3 Years",
          breed: "Griffon",
          gender: "Male",
          neutered: "Yes",
          location: "Alexandria",
          image: "images/buddy.jpg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Fosdo'a",
          age: "4 Years",
          breed: "Balady",
          gender: "Female",
          neutered: "No",
          location: "Giza",
          image: "images/fosdo2a.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Max",
          age: "1 Year",
          breed: "Golden Retriever",
          gender: "Male",
          neutered: "No",
          location: "Giza",
          image: "images/Max.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Oreo",
          age: "4 1/2 Years",
          breed: "Cocker Spaniel",
          gender: "Male",
          neutered: "No",
          location: "Port Said",
          image: "images/oreo.png",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Reeses",
          age: "5 Months",
          breed: "Rottweiler",
          gender: "Male",
          neutered: "No",
          location: "Port Said",
          image: "images/reeses.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Steve",
          age: "3 Years",
          breed: "Corgi",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/steve.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Zaatar",
          age: "9 Months",
          breed: "Golden Retriever",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/Zaatar.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Milo",
          age: "3 Years",
          breed: "Volpino",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/milo.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Bruce",
          age: "3 Years",
          breed: "Pitbull",
          gender: "Male",
          neutered: "No",
          location: "Ismailia",
          image: "images/bruce.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Bruno",
          age: "1 Year",
          breed: "German Shepherd",
          gender: "Male",
          neutered: "No",
          location: "Giza",
          image: "images/bruno.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Casper",
          age: "2 Years",
          breed: "Volpino",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/casper.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Daisy",
          age: "7 Months",
          breed: "Cocker Spaniel",
          gender: "Female",
          neutered: "No",
          location: "Cairo",
          image: "images/daisy.jpeg",
          type: "dog",
          upForAdoption: true
        },
        {
          name: "Zoro",
          age: "5 Months",
          breed: "Cocker Spaniel",
          gender: "Male",
          neutered: "No",
          location: "Cairo",
          image: "images/zoro.jpeg",
          type: "dog",
          upForAdoption: true
        },
];

Pet.insertMany(pets).then(() => {
  console.log('Pets seeded!');
  mongoose.disconnect();
});